import React from 'react';
import { Drawer as FlowbiteDrawer, DrawerItems } from 'flowbite-react';
import { Scale, Lock as ShieldCheck, Cookie, Phone as Headset, X, CheckCircle as CheckCircle2, Mail, ExternalLink, Phone, MessageSquare, AlertCircle as HelpCircle } from './icons/FlowbiteIcons';
import { WhatsappIcon } from './icons/WhatsappIcon';
import { TelegramIcon } from './icons/TelegramIcon';
import { Button } from './Button';

export type LegalTabType = 'terms' | 'privacy' | 'cookies' | 'support' | 'faq' | null;

interface LegalDrawerProps {
  activeTab: LegalTabType;
  onClose: () => void;
}

export const LegalDrawer: React.FC<LegalDrawerProps> = ({ activeTab, onClose }) => {
  const isOpen = activeTab !== null;

  return (
    <FlowbiteDrawer
      open={isOpen}
      onClose={onClose}
      position="right"
      className="w-full max-w-xl bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-800 shadow-2xl flex flex-col z-9999 font-sans"
    >
      {/* Header Row */}
      <div className="p-4 sm:p-5 border-b border-slate-200 dark:border-slate-800 bg-slate-900 text-white flex items-center justify-between shrink-0 rounded-tl-lg">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-blue-600/30 border border-blue-500/40 text-blue-400 flex items-center justify-center shrink-0">
            {activeTab === 'terms' && <Scale className="w-5 h-5" />}
            {activeTab === 'privacy' && <ShieldCheck className="w-5 h-5 text-emerald-400" />}
            {activeTab === 'cookies' && <Cookie className="w-5 h-5 text-amber-400" />}
            {activeTab === 'support' && <Headset className="w-5 h-5 text-sky-400" />}
            {activeTab === 'faq' && <HelpCircle className="w-5 h-5 text-purple-400" />}
          </div>
          <div>
            <h3 className="text-base font-bold text-white leading-tight">
              {activeTab === 'terms' && 'Terms of Service'}
              {activeTab === 'privacy' && 'Privacy Policy'}
              {activeTab === 'cookies' && 'Cookie Policy'}
              {activeTab === 'support' && 'Contact Support'}
              {activeTab === 'faq' && 'Frequently Asked Questions'}
            </h3>
            <p className="text-2xs text-slate-400 font-medium">Ground Code™ SaaS Platform & Policy Agreement</p>
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="text-slate-400 hover:text-white rounded-lg p-1.5 hover:bg-slate-800 transition-colors cursor-pointer"
          aria-label="Close drawer"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      {/* Drawer Body Items */}
      <DrawerItems className="flex-1 overflow-y-auto p-5 sm:p-6 text-xs text-slate-700 dark:text-slate-200 leading-relaxed space-y-5">
        {activeTab === 'terms' && (
          <div className="space-y-4">
            <div className="p-3.5 bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 rounded-xl space-y-1">
              <div className="flex items-center gap-1.5 font-bold text-emerald-800 dark:text-emerald-300 text-xs">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                <span>1-Month Free Trial • No Credit Card Required • No Lock-In</span>
              </div>
              <p className="text-2xs text-emerald-700 dark:text-emerald-400 leading-normal">
                Every property receives a 30-Day Free Trial. Billed at ₹1,499/month (includes 1st room key) + ₹350/extra key/month after trial via direct manual invoice.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm">1. GroundCode Pro Subscription Model</h4>
              <p>
                Ground Code operates on a single unified Pro plan. Subscriptions are billed directly via manual invoices managed by Root Admin. No automated card debits are performed without your explicit consent.
              </p>

              <h4 className="font-bold text-slate-900 dark:text-white text-sm">2. 100% Data Ownership & Tenant Isolation</h4>
              <p>
                All guest records, stay folios, meal logs, petty cash vouchers, and inventory data generated by your property remain your exclusive property. Ground Code claims zero ownership over subscriber data and enforces database-level tenant isolation.
              </p>

              <h4 className="font-bold text-slate-900 dark:text-white text-sm">3. Staff Access Security</h4>
              <p>
                Property Owners are responsible for assigning, maintaining, and revoking staff PINs and access roles (e.g. Supervisor, Front-Desk, Kitchen Staff).
              </p>

              <h4 className="font-bold text-slate-900 dark:text-white text-sm">4. Cancellation & Data Export</h4>
              <p>
                Subscribers may cancel their subscription at any time without lock-in commitment. Prior to cancellation, subscribers can request a full data export in CSV/JSON format.
              </p>
            </div>
          </div>
        )}

        {activeTab === 'privacy' && (
          <div className="space-y-4">
            <div className="p-3.5 bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800/60 rounded-xl space-y-1">
              <div className="flex items-center gap-1.5 font-bold text-blue-900 dark:text-blue-300 text-xs">
                <ShieldCheck className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" />
                <span>STRICT ZERO DATA SELLING GUARANTEE</span>
              </div>
              <p className="text-2xs text-blue-800 dark:text-blue-400 leading-normal">
                Ground Code NEVER sells, rents, or monetizes property data, guest databases, or financial income records to third-party ad networks or OTAs.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm">1. Information We Collect</h4>
              <p>
                We collect information strictly necessary to operate your homestay management dashboard: property name, owner phone number (for OTP authentication), guest names, check-in/out dates, and guest ID proof uploads.
              </p>

              <h4 className="font-bold text-slate-900 dark:text-white text-sm">2. Police Verification & C-Form Document Protection</h4>
              <p>
                Guest ID document uploads (Aadhaar, Passport, Driving License) are stored encrypted and accessible strictly by authorized property staff to assist hosts in fulfilling statutory police verification registers.
              </p>

              <h4 className="font-bold text-slate-900 dark:text-white text-sm">3. Security & Encryption</h4>
              <p>
                Data in transit is encrypted using standard TLS/HTTPS encryption. Staff PIN credentials and passwords are stored using one-way cryptographic hashing algorithms.
              </p>
            </div>
          </div>
        )}

        {activeTab === 'cookies' && (
          <div className="space-y-4">
            <div className="p-3.5 bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/60 rounded-xl space-y-1">
              <div className="flex items-center gap-1.5 font-bold text-amber-900 dark:text-amber-300 text-xs">
                <Cookie className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
                <span>Essential Session Cookies Only</span>
              </div>
              <p className="text-2xs text-amber-800 dark:text-amber-400 leading-normal">
                Ground Code uses session tokens strictly to keep your staff logged into the dashboard securely. We do not use third-party ad tracking cookies.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-bold text-slate-900 dark:text-white text-sm">1. Session Tokens & Context</h4>
              <p>
                Session cookies and local storage tokens keep property owners and staff logged in across sessions, remember selected property context (<code className="bg-slate-100 dark:bg-slate-800 px-1 py-0.5 rounded">tenant_id</code>), and authorize secure API requests.
              </p>

              <h4 className="font-bold text-slate-900 dark:text-white text-sm">2. No Cross-Site Ad Telemetry</h4>
              <p>
                No third-party advertising cookies or cross-site tracking pixels are executed inside your property operational control panel.
              </p>
            </div>
          </div>
        )}

        {activeTab === 'support' && (
          <div className="space-y-4">
            <div className="p-3.5 bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-800/60 rounded-xl space-y-1">
              <div className="flex items-center gap-1.5 font-bold text-sky-900 dark:text-sky-300 text-xs">
                <Headset className="w-4 h-4 text-sky-600 dark:text-sky-400 shrink-0" />
                <span>Ground Code Dedicated Support</span>
              </div>
              <p className="text-2xs text-sky-800 dark:text-sky-400 leading-normal">
                Our support team is available 7 days a week to assist with property configuration, staff PINs, KDS menus, and iCal calendar setup.
              </p>
            </div>

            {/* Real click-to-chat links (27 Aug 2026) - see ContactSupportMenu.tsx,
                which is what actually opens this tab now. Kept separate from the
                informational cards below since those describe unrelated things
                (the automated per-property alerts bot, a scheduled call) rather
                than being contact links themselves. */}
            <div className="grid grid-cols-2 gap-3">
              <a
                href="https://wa.me/919571263474"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 p-3 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800/60 rounded-xl text-emerald-800 dark:text-emerald-300 font-semibold text-xs hover:bg-emerald-100 dark:hover:bg-emerald-950/50 transition-colors"
              >
                <WhatsappIcon className="w-4 h-4 shrink-0" />
                <span>WhatsApp</span>
              </a>
              <a
                href="https://t.me/GroundCodeCom"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 p-3 bg-sky-50 dark:bg-sky-950/30 border border-sky-200 dark:border-sky-800/60 rounded-xl text-sky-800 dark:text-sky-300 font-semibold text-xs hover:bg-sky-100 dark:hover:bg-sky-950/50 transition-colors"
              >
                <TelegramIcon className="w-4 h-4 shrink-0" />
                <span>Telegram</span>
              </a>
            </div>

            <div className="space-y-3">
              <div className="p-4 bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/80 rounded-xl space-y-3">
                <div className="flex items-center gap-3">
                  <Mail className="w-4 h-4 text-blue-600 dark:text-blue-400 shrink-0" />
                  <div>
                    <span className="font-bold text-slate-900 dark:text-white block">Email Support</span>
                    <a href="mailto:support@ground-code.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                      support@ground-code.com
                    </a>
                  </div>
                </div>

                <div className="flex items-center gap-3 border-t border-slate-200 dark:border-slate-700 pt-3">
                  <MessageSquare className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                  <div>
                    <span className="font-bold text-slate-900 dark:text-white block">Telegram Staff Alerts Bot</span>
                    <span className="text-2xs text-slate-500 dark:text-slate-400">Native automated property alerts & KDS notifications</span>
                  </div>
                </div>

                <div className="flex items-center gap-3 border-t border-slate-200 dark:border-slate-700 pt-3">
                  <Phone className="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
                  <div>
                    <span className="font-bold text-slate-900 dark:text-white block">Guided Onboarding Setup Call</span>
                    <span className="text-2xs text-slate-500 dark:text-slate-400">Schedule your personal 30-minute 1-on-1 setup session</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'faq' && (
          <div className="space-y-4">
            <div className="p-3.5 bg-purple-50 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-800/60 rounded-xl space-y-1">
              <div className="flex items-center gap-1.5 font-bold text-purple-900 dark:text-purple-300 text-xs">
                <HelpCircle className="w-4 h-4 text-purple-600 dark:text-purple-400 shrink-0" />
                <span>Frequently Asked Questions (FAQ)</span>
              </div>
              <p className="text-2xs text-purple-800 dark:text-purple-400 leading-normal">
                Everything homestay hosts and resort owners need to know about pricing, setup, calendar sync &amp; compliance.
              </p>
            </div>

            <div className="space-y-3">
              {/* Category 1: General & Pricing */}
              <div className="pt-1">
                <span className="text-2xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider block mb-2">General &amp; Subscription</span>
                
                <div className="space-y-2.5">
                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: What is Ground Code?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      Ground Code is a specialized property management system (PMS) designed for homestays, villas, guest houses, and boutique resorts in India. It helps hosts manage bookings, guest check-ins, kitchen orders (KDS), petty cash, and staff attendance with zero booking commission.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: How does the 30-Day Free Trial work?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      You get 100% full access to GroundCode Pro for 30 days without entering a credit card or signing a contract. Our team hops on a personal 1-on-1 setup call to help configure your room keys, staff PINs, and booking calendar.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: How much does Ground Code cost after the trial?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      Ground Code operates on ONE single simple plan: <strong>GroundCode Pro</strong> at ₹1,499/month (includes 1st villa or room key). Extra room keys cost just +₹350/room/month. You can also save 2 months free with annual billing (₹14,990/year).
                    </p>
                  </div>
                </div>
              </div>

              {/* Category 2: Bookings & OTA Calendar Sync */}
              <div className="pt-2">
                <span className="text-2xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider block mb-2">Bookings &amp; iCal Calendar Sync</span>

                <div className="space-y-2.5">
                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: Do you charge any booking commission?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      No, never! Ground Code charges ZERO commission on any booking. Unlike OTAs that take 15–25% per reservation, you keep 100% of your guest revenue.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: How does calendar sync with Airbnb &amp; Booking.com work?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      We provide standard iCal (.ics) feed synchronization. Import and export links automatically poll availability across your connected OTAs with a ~15–30 minute update window.
                    </p>
                  </div>
                </div>
              </div>

              {/* Category 3: Staff Roles & Kitchen KDS */}
              <div className="pt-2">
                <span className="text-2xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider block mb-2">Staff Roles &amp; Kitchen (KDS)</span>

                <div className="space-y-2.5">
                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: Can my cook and front-desk staff use different screens?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      Yes! You can assign specific staff roles and PINs. Your cook gets a Kitchen Order Screen (KDS), front-desk staff get guest check-in &amp; petty cash tools, while revenue reports remain private to the owner.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: How do Telegram phone alerts work?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      You can connect your property's Telegram bot in 2 minutes to receive instant phone alerts for new guest bookings, check-in arrivals, and cash drawer adjustments.
                    </p>
                  </div>
                </div>
              </div>

              {/* Category 4: Data Privacy & Compliance */}
              <div className="pt-2">
                <span className="text-2xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider block mb-2">Data Protection &amp; Compliance</span>

                <div className="space-y-2.5">
                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: Is my property and guest data safe?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      100% safe. We enforce a strict Zero Data Selling Guarantee. Your guest lists, ID proofs, and property income logs are private to your property and never shared or sold to third parties or OTAs.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 rounded-xl">
                    <h4 className="font-bold text-slate-900 dark:text-white text-xs mb-1">Q: Does Ground Code support Police C-Form &amp; GST compliance?</h4>
                    <p className="text-2xs text-slate-600 dark:text-slate-300 leading-relaxed">
                      Yes! Ground Code stores encrypted guest ID proofs (Aadhaar, Passport) to help hosts fulfill statutory police verification registers, and generates GST-compliant guest bills and invoices.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </DrawerItems>

      {/* Drawer Footer Actions */}
      <div className="p-4 border-t border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-850 flex items-center justify-between shrink-0">
        <a
          href="./TERMS_AND_PRIVACY.md"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-2xs font-semibold text-blue-600 dark:text-blue-400 hover:underline"
        >
          <span>Open Full Documentation (.md)</span>
          <ExternalLink className="w-3 h-3" />
        </a>
        <Button variant="secondary" size="xs" onClick={onClose}>
          Close
        </Button>
      </div>
    </FlowbiteDrawer>
  );
};
